### ISSUE TITLE
Host Card Emulation HCE on Android get card owner

### ISSUE THREAD

**Issue by braysonjohn148** [vlast3k/Arduino-libraries#1]
Android provides a different card ID with each tap. I need to know this card belongs to who, and how can I get the owner.

Android Code:
  String cardAid,
  String cardUid, [
  String aesKey,]
 NfcEmulator.startNfcEmulator("00A40400F0010203040506","cd22c716", "79e64d05ed6475dcd506b");
Can I use the UID and the AES key to decode and get the card ID? Or how does it work

**Comment by vlast3k** [comment]
Hi, just FYI, this is just a copy of some libraries, stored for some reason in my repo. 
Better find a more suitable repo to open an issue to, if you want to get help
